// LedgerZero workflow: "Recording bank account transactions manually" (Impl Spec §7.5.2).
// Generated by the dev-time backend from a deterministic template
// (Impl Plan M8, devtime/generator.py) — no hand-edits. Same standalone-
// artifact shape as every hand-written workflow (Impl Spec §7.1): its own
// vendored React copy, no shared JavaScript with the launcher or any other
// workflow. book_id/entity_id come from the URL query string (the launcher
// supplies them); workflow_id/workflow_deployment_id identify this
// deployed artifact and are fixed at generation/deploy time.
const WORKFLOW_ID = "caa68822-668f-4e14-a01b-d5dced2d260d";
const WORKFLOW_DEPLOYMENT_ID = "aa954a75-7f7f-4f7f-bee2-62e625eaef9f";

const e = React.createElement;

function useQueryParam(name) {
  return new URLSearchParams(window.location.search).get(name);
}

async function api(path, options) {
  const response = await fetch(path, {
    credentials: "same-origin",
    headers: { "Content-Type": "application/json" },
    ...options,
  });
  const body = await response.json().catch(() => ({}));
  return { ok: response.ok, status: response.status, body };
}

function todayIso() {
  return new Date().toISOString().slice(0, 10);
}

const FIELDS = [
  {
    "id": "transactionDate",
    "label": "Transaction date",
    "type": "date",
    "required": true
  },
  {
    "id": "description",
    "label": "Description",
    "type": "text",
    "required": true,
    "placeholder": "e.g. Wire from customer"
  },
  {
    "id": "amount",
    "label": "Amount",
    "type": "number",
    "required": true
  },
  {
    "id": "direction",
    "label": "Direction",
    "type": "select",
    "required": true,
    "options": [
      [
        "deposit",
        "Deposit (money in)"
      ],
      [
        "withdrawal",
        "Withdrawal (money out)"
      ]
    ]
  },
  {
    "id": "bankAccountId",
    "label": "Bank account (account_id)",
    "type": "account",
    "required": true,
    "placeholder": "account UUID"
  },
  {
    "id": "offsetAccountId",
    "label": "Offset account (account_id)",
    "type": "account",
    "required": true,
    "placeholder": "account UUID"
  },
  {
    "id": "reference",
    "label": "Reference / memo",
    "type": "text",
    "required": false
  }
];

function buildLines(form) {
  const primaryIsDebit = form.direction === "deposit";
  return [
    {
      line_id: crypto.randomUUID(),
      account_id: form.bankAccountId,
      debit_amount: primaryIsDebit ? form.amount : null,
      credit_amount: primaryIsDebit ? null : form.amount,
      memo: form.reference || null,
    },
    {
      line_id: crypto.randomUUID(),
      account_id: form.offsetAccountId,
      debit_amount: primaryIsDebit ? null : form.amount,
      credit_amount: primaryIsDebit ? form.amount : null,
      memo: form.reference || null,
    },
  ];
}

function renderField(f, form, setField) {
  const commonProps = {
    required: f.required,
    value: form[f.id],
    onChange: setField(f.id),
  };
  const input =
    f.type === "select"
      ? e(
          "select",
          commonProps,
          e("option", { value: "" }, "Choose…"),
          ...f.options.map(([value, label]) =>
            e("option", { key: value, value }, label)
          )
        )
      : e("input", {
          type: f.type === "account" ? "text" : f.type,
          placeholder: f.placeholder || undefined,
          step: f.type === "number" ? "0.01" : undefined,
          min: f.type === "number" ? "0.01" : undefined,
          ...commonProps,
        });
  return e("label", { key: f.id }, f.label, input);
}

function App() {
  const bookId = useQueryParam("book_id");
  const entityId = useQueryParam("entity_id");

  const [me, setMe] = React.useState(null);
  const [authorized, setAuthorized] = React.useState(null);
  const [form, setForm] = React.useState({
    transactionDate: todayIso(),
    description: "",
    amount: "",
    direction: "",
    bankAccountId: "",
    offsetAccountId: "",
    reference: "",
  });
  const [result, setResult] = React.useState(null);
  const [error, setError] = React.useState(null);
  const [submitting, setSubmitting] = React.useState(false);

  React.useEffect(() => {
    if (!bookId || !entityId) return;
    api("/api/auth/me").then((r) => setMe(r.ok ? r.body : null));
    api(`/api/books/${bookId}/workflows/mine?entity_id=${entityId}`).then(
      (r) => {
        setAuthorized(
          r.ok && r.body.some((w) => w.workflow_id === WORKFLOW_ID)
        );
      }
    );
  }, [bookId, entityId]);

  function setField(name) {
    return (ev) => setForm({ ...form, [name]: ev.target.value });
  }

  async function submit(ev) {
    ev.preventDefault();
    setError(null);
    setSubmitting(true);
    const executionId = crypto.randomUUID();
    const response = await api(`/api/books/${bookId}/entries`, {
      method: "POST",
      body: JSON.stringify({
        entry_id: crypto.randomUUID(),
        entity_id: entityId,
        entry_date: form.transactionDate,
        description: form.description,
        source: "WORKFLOW",
        workflow: {
          workflow_id: WORKFLOW_ID,
          workflow_deployment_id: WORKFLOW_DEPLOYMENT_ID,
          workflow_execution_id: executionId,
        },
        lines: buildLines(form),
      }),
    });
    setSubmitting(false);
    if (response.ok) {
      setResult({ entryId: response.body.id, executionId });
      setForm({ ...form, description: "", amount: "", reference: "" });
    } else {
      setError(response.body);
    }
  }

  if (!bookId || !entityId) {
    return e(
      "div",
      { className: "box" },
      e("h1", null, "Recording bank account transactions manually"),
      e(
        "p",
        { className: "error" },
        "Open this workflow from the LedgerZero launcher's workflow menu " +
          "(it needs book_id and entity_id, missing from this URL)."
      )
    );
  }

  return e(
    "div",
    { className: "box" },
    e("h1", null, "Recording bank account transactions manually"),
    me && e("p", { className: "muted" }, `Signed in as ${me.user.email}`),
    authorized === false &&
      e(
        "p",
        { className: "error" },
        "You are not currently authorized to run this workflow for this " +
          "entity — the server will reject any submission."
      ),
    e(
      "form",
      { onSubmit: submit },
      ...FIELDS.map((f) => renderField(f, form, setField)),
      e(
        "button",
        { type: "submit", disabled: submitting },
        submitting ? "Recording…" : "Record transaction"
      )
    ),
    result &&
      e(
        "p",
        { className: "success" },
        `Posted entry ${result.entryId} (execution ${result.executionId}).`
      ),
    error &&
      e(
        "p",
        { className: "error" },
        `${error.error_code || "ERROR"}: ${error.message || "request failed"}`
      )
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(e(App));
